version: '3.8'

services:


  # MySQL service
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  # # Adminer service for MySQL
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8082:8080 